// <auto-generated />
using Microsoft.Extensions.DependencyInjection;
using App.Services.Audit;
using App.Services.Calendar;
using App.Services.Common;
using App.Services.Correspondences;
using App.Services.Directory;
using App.Services.Files;
using App.Services.Installation;
using App.Services.Institutions;
using App.Services.Localization;
using App.Services.Notifications;
using App.Services.Registrations;
using App.Services.Reports;
using App.Services.Security;
using App.Services.Settings;
using App.Services.Templates;
using App.Services.Users;

namespace App.Services
{
    /// <summary>
    /// Central DI registration for App.Services
    /// </summary>
    public static class AppServicesStartup
    {
        /// <summary>
        /// Registers all service interfaces to their implementations.
        /// Call this from Program.cs: builder.Services.AddAppServices();
        /// </summary>
        public static IServiceCollection AddAppServices(this IServiceCollection services)
        {
            return services;
        }
    }
}

